### ISSUE TITLE
ERROR: core-image-sato-1.0-r0 do_rootfs: Could not invoke dnf.

### ISSUE THREAD

**Issue by kartikeyparmar** [intel/iotg-yocto-bsp-public#10]
I have recently upgraded Yocto BSP from E3900-MR3.1 to MR4-B-01 branch.

During core-image-sato do_rootfs task, it throws an error

**ERROR: core-image-sato-1.0-r0 do_rootfs: Could not invoke dnf.** 
Error: 
 Problem: conflicting requests
  - nothing provides libc.so.6(GLIBC_2.15) needed by codemeter-6.81.3477+500-r0.corei7_64

Here, we have a custom recipe for codemeter-6.81.3477 (codemeter rpm to install in rootfs).
Just FYI, The same recipe with E3900-MR3.1 branch build completes successfully.

**Comment by chongyic** [comment]
Hi @kartikeyparmar,
libc.so.6 is provided by glibc package. Could you confirm your recipe did mentioned the runtime dependencies (RDEPENDS) correctly?
