### ISSUE TITLE
Intel Oxbow Hill CRB (Rev B) - Linux Yocto image (Tag: E3900-MR2) has no audio output on speaker / headset

### ISSUE THREAD

**Issue by kartikeyparmar** [intel/iotg-yocto-bsp-public#2]
**Brief Description:**
I have an Intel Oxbow Hill CRB (Rev B) running with Yocto image (compiled with E3900-MR2 release).
When I open a video clip (Wildlife.wmv) in "Basic Media Player", it only shows video output but there is no audio output on speaker / headset.

**Setup Information:**
---------------------------------------------------------------------------------------------------------------
_**Board:**_ Intel Oxbow Hill CRB (Rev B)
_**BIOS Information:**_
BIOS Vendor                      :American Megatrends
Core version                      : 5.12
Compliancy                       :UEFI 2.5; PI 1.4
Project Version                 :1ATJS 0.27 x64
Build Date  and Time        : 12/15/2016    18:45:06  
Access level                       :Administrator

_**Platform firmware Information:**_
BXT SOC                             :B1
MRC Version                      :0.56
PUNTT FW                          :30
PMC FW                             :03.26
TXE FW                               :3.0.11.1131
ISH FW                               :4.1.0.3364
GOP                                    :10.0.0.1035
CPU Flavor                         :BXT Notebook/Desktop ...
Board ID                             :Oxbow Hill CRB (06)
Fab ID                                :FAB B

Total memory                    : 8192 MB.
OS Selection                      : Intel Linux

**_BIOS Setting for HD Audio:_**
Chipset-> South Cluster Configuration -> HD-Audio Configuration -> HD-Audio I/O Buffer Ownership Select to "HD-Audio link owns all the I/O buffers".

**_OS information:_**
GIT repository                     : https://github.com/01org/iotg-yocto-bsp-public.git
GIT Tag                               : E3900-MR2
Linux Kernel version          : 4.1.27-yocto-standard
Audio driver selection       : CAVS HD Audio driver (Default)
Image Type                       : core-image-sato (.hddimage)

---------------------------------------------------------------------------------------------------------------

**Steps to reproduce:**
(1) Build core-image-sato image using default audio driver selection (CAVS HD Audio driver)
(2) Install core-image-sato .hddimage into a HDD connected to Intel Oxbow Hill CRB
(3) Goto BIOS setup to change suggested "HD Audio I/O Buffer" selection
(4) Save BIOS settings and boot Yocto from HDD
(5) Edit .xinitrd to enable "matchbox-session" and disable "xterm"
(6) Use "startx" to start X-Windows session
(7) Open "Media Player"
(8) Select video clip "Wildlife.wmv" to play
**Note:** Wildlife.wmv video clip is available in sample video under Windows 7 (64-bit)

**Observation:**
There is only video output on the screen and no audio output on Speaker / headset.

**Other investigations:**
(1) Open "Terminal"
(2) Issue command "aplay -l" to list all available soundcards / digital audio devices. It is listing "ALC662" 
     (Ref: Attached "aplay.txt")
(3) Use "speaker-test -Dfront:PCH -c 2" and you are able to hear stereo audio output on the headset.

[aplay.txt](https://github.com/01org/iotg-yocto-bsp-public/files/1006320/aplay.txt)

**Comment by chongyic** [comment]
Hi @kartikeyparmar ,

Can you check if the sound is playing in either 
1. DP
2. HDMI
3. Analogue output?

If the sound appear in either of the output mentioned above, then it would require changes in configuration for audio to play in desire output channel.

Thank you.

**Comment by kimhoemo** [comment]
Hi @kartikeyparmar 
Seems like you have successfully build the image and booted up on Intel APL-I CRB (Oxbow). For the issue that you observed, please file a case to Intel Premier Support (IPS) so that we can support you better. 

Thanks.

**Comment by kartikeyparmar** [comment]
Hi @kimhoemo 
I had already filed a case to Intel Premier Support (IPS).
Kindly refer to Case [00177038](https://shnintel31crm.intel.myshn.net/IPS/500o000000RKN1j) 
Thanks.

**Comment by kimhoemo** [comment]
Hi @kartikeyparmar 
Thanks. Our front line will provide input to you soonest. 
Thank you for your patient.

**Comment by kartikeyparmar** [comment]
Hi @chongyic 

Here is my finding:
(1) HDMI: Can play both Video and Audio.
(2) DP: Can only play Video, No audio out.
(3) Analog output: Can play Audio on Speaker-out .
     (Use cmd: **speaker-test -c 2 -t wav -D sysdefault:PCH -p 10000 > /dev/null &**)

Kindly refer to attached log for "aplay -l and pactl list sinks" command output.

I have already tried "alsamixer" but it doesn't work.
Which configuration are you referring to?
Thanks.
[pactl_and_aplay_log.txt](https://github.com/01org/iotg-yocto-bsp-public/files/1018435/pactl_and_aplay_log.txt)

**Comment by kartikeyparmar** [comment]
Hi @chongyic and @kimhoemo 

I referred to **aplay -l** output and found that Card 0, Device 0 is **ALC662 rev3 Analog** playback device.
I referred to **pactl list sinks** output and found the default playback device is set to **HDMI 0**

I have edited "/etc/pulse/default.pa" and change below line to:
load-module module-alsa-sink device=hw:0,0

This has set default playback device to **ALC662 rev3 Analog** and I am able to get audio playback while playing video file under Media Player.

Thanks.
