### ISSUE TITLE
Delay when typing on cmd prompt and Gstreamer vappi out of date in middleware layer

### ISSUE THREAD

**Issue by bgiles12** [intel/iotg-yocto-bsp-public#5]
My company is considering using the Apollo Lake Platform for our next embedded design. I have an Oxbow Hill board from Intel and a Gigabyte board with the Apollo Lake N3350. From the MR3.1 image we have noticed a delay when trying to run simple commands, like ls, from the command prompt. If we put Ubuntu 16.04 on the same unit we do not see the issue. We suspect this to be a kernel issue as the current Yocto BSP is based on Jethro. 
I have been digging through the 100s of documents from the APL RDC. In one of the documents, "Apollo Lake - Apollo Lake-I Dashboard-Lite," there is a page for the IOTG Apollo Lake Platform Schedules. It shows a MR4 release of the Yocto Project in May'18 with the note that "This is an alpha quality release." I have asked my local Intel Representative and IPS for the changes between MR3.1 and the upcoming MR4 release. IPS has responded that they do not know the differences and I haven't heard back from the Intel Rep.
Will MR4 use a later Yocto Core (Morty, Pyro, Rocko?) thus updating the kernel?
Will later libraries for Gstreamer vappi be used?

**Comment by kimhoemo** [comment]
@bgiles12 Thank you for your issue submission. Please provide IPS case number and I shall look for right person to provide you further assistance through IPS.

**Comment by bgiles12** [comment]
@kimhoemo Thanks for the response. Here is my case number 00224570.

**Comment by bgiles12** [comment]
@kimhoemo With the Oxbow Hill board this is a none issue except the second part. Do you want to close this issue and open another on here. I have a new case number for the GStreamer out of date in the middleware layer (00227216)

**Comment by cchuanung** [comment]
Brent Giles,
            Please proceed the communication through the IPS number 00224570 as stated in another email and close the case at this github.

Regards,
Cheng Chuan
