### ISSUE TITLE
I2S Ports are not available in MR4 configuration

### ISSUE THREAD

**Issue by bgiles12** [intel/iotg-yocto-bsp-public#9]
I have a design which has the Realtek ALC255 audio codec which uses the HD Audio configuration. I want to hook up an external DSP to the I2S1 and I2S2 ports and keep the audio codec to manage the speaker and headset jack. The external DSP already has a linux driver which my software team has successfully ported but cannot find where to enable the I2S ports. I have and open case in the Intel Portal (00431323). I am having them verify the architecture works but either way I need to know how to configure the kernel to allow access to the I2S ports.

**Comment by chongyic** [comment]
Hi @bgiles12 ,

Please submit you question in the same case in Intel Portal (00431323) for your question related to your configuration.
Thanks.

**Comment by bgiles12** [comment]
Hello @chongyic,
I have updated the case with my question and was asked to identify who you were so I commented you were a contributor to this repository and have not received any feedback yet.

Would you know if I can have HD Audio and an I2S peripheral enabled simultaneously on the Apollo Lake?

**Comment by chongyic** [comment]
> Hello @chongyic,
> I have updated the case with my question and was asked to identify who you were so I commented you were a contributor to this repository and have not received any feedback yet.
> 
> Would you know if I can have HD Audio and an I2S peripheral enabled simultaneously on the Apollo Lake?

Hi @bgiles12 ,
Only one option can be built at a time in kernel and thus you cannot have both HD Audio and an I2S peripheral enabled simultaneously on the Apollo Lake.
